#! variables that need to be externally configurable
#! are specified in a data values schema file

#@ load("@ytt:data", "data")
#@ if hasattr(data.values, "secretmanager") and 'aws' in data.values.secretmanager:
#@ end
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/team-a
  name: my-serviceaccount
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount